# Generated by Django 4.1.6 on 2023-02-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_record_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='day',
            field=models.DateField(),
        ),
    ]
