# Generated by Django 4.1.6 on 2023-02-06 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_record_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
