# Generated by Django 4.1.6 on 2023-02-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_record_user_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
