# Generated by Django 4.1.6 on 2023-02-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_record_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='hour1',
            new_name='hour',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour2',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour3',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour4',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour5',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour6',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour7',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour8',
        ),
    ]
