# Generated by Django 4.1.6 on 2023-02-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_hour1_record_hour_remove_record_hour2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='hour',
            new_name='hour1',
        ),
        migrations.AddField(
            model_name='record',
            name='hour2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='hour3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='hour4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='hour5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='hour6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='hour7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='hour8',
            field=models.BooleanField(default=False),
        ),
    ]
