# Generated by Django 4.1.6 on 2023-03-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_hour_record_hour1_record_hour2_record_hour3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dept',
            field=models.CharField(default='', max_length=50),
        ),
    ]
