# Generated by Django 4.1.6 on 2023-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_record_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sem',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='record',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
